exp_name: sac_rho_2
model: sac
env_name: bertrand
use_lstm: False
n_actions: 1

env: # environment params
  N: 2
  k: 1
  v: 3
  rho: 0.0005
  xi: 0.2

agent: # agent params
  actor_lr: 0.0001
  Q_lr: 0.0003
  gamma: 0.95
  tau: 0.01
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 100_000

train: # train params
  episodes: 1
  timesteps: 100_000
  inflation_start: 0
  trigger_deviation: False
  update_steps: 1