exp_name: exp_01
model: ddpg
use_lstm: True
n_actions: 1

env: # environment params
  N: 2
  k: 1
  v: 3
  rho: 0.0001
  xi: 0.2

agent: # agent params
  actor_lr: 0.01
  Q_lr: 0.01
  gamma: 0.99
  tau: 0.001
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 1_000_000

train: # train params
  timesteps: 1000
  learning_start: 1000
  update_steps: 1