exp_name: sac_k_1
model: sac
env_name: linear
use_lstm: False
n_actions: 1

env: # environment params
  N: 2
  k: 5
  v: 6
  rho: 0.0001
  xi: 0.2

agent: # agent params
  actor_lr: 0.0001
  Q_lr: 0.0003
  gamma: 0.99
  tau: 0.01
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 100_000

train: # train params
  timesteps: 100_000
  inflation_start: 20_000
  trigger_deviation: False
  update_steps: 1