exp_name: sac_N_1
model: sac
env_name: linear
use_lstm: False
n_actions: 1

env: # environment params
  N: 5
  k: 1
  v: 3
  rho: 0.002
  xi: 0.2

agent: # agent params
  actor_lr: 0.0001
  Q_lr: 0.0003
  gamma: 0.99
  tau: 0.01
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 100_000

train: # train params
  episodes: 100
  timesteps: 10_000
  inflation_start: 0
  trigger_deviation: False
  update_steps: 1